# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
# relative_permalinks: true

# Setup
title:            numericalshadow.org
tagline:          ''
description:      ''
baseurl:          /
repository:        iitis/numericalshadow.org

author:
  name:           'Lukasz Pawela'

paginate:         5

# Custom vars
version:          0.0.1

plugins:
  - jekyll-latex
  - jekyll-scholar

github:
  repo:           https://github.com/iitis/numericalshadow.org

scholar:
  style: ieee
  source:	./_bibliography
  bibliography:	references.bib
  bibliography_template: bib

# remote_theme: pmarsceill/just-the-docs
# remote_theme: iitis/just-the-docs
remote_theme: thealjey/just-the-docs
color_scheme: dark
logo: /assets/logo.png
search_enabled: false
aux_links:
  "numericalshadow.org on GitHub":
    - "//github.com/iitis/numericalshadow.org"

aux_links_new_tab: true

domain: iitis.github.io
url: https://iitis.github.io
baseurl: /numericalshadow.org/

# exclude: ["docker-compose.yml"]
