# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
# relative_permalinks: true

# Setup
title:            numericalshadow.org
tagline:          ''
description:      ''
baseurl:          /

author:
  name:           'Lukasz Pawela'

paginate:         5

# Custom vars
version:          0.0.1

plugins:
  - jekyll-latex
  - jekyll-scholar

github:
  repo:           https://github.com/iitis/numericalshadow.org

scholar:
  style: modern-language-association
  source:	./_bibliography
  bibliography:	references.bib

remote_theme: pmarsceill/just-the-docs
color_scheme: dark

domain: iitis.github.io
url: https://iitis.github.io
baseurl: /numericalshadow.org

exclude: ["src/numerical-range/generalizations/normalized-numerical-range.md"]
