# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
# relative_permalinks: true

# Setup
title:            numericalshadow.org
tagline:          ''
description:      ''
baseurl:          /shadow
repository:       numericalshadow/numericalshadow.org
domain:           numericalshadow.org
url:              https://numericalshadow.org

author:
  name:           'Lukasz Pawela'

paginate:         5

# Custom vars
version:          0.1.0

plugins:
  - jekyll-latex
  - jekyll-scholar


scholar:
  style: ieee
  source:	./_bibliography
  bibliography:	references.bib
  bibliography_template: bib

# remote_theme: pmarsceill/just-the-docs
# remote_theme: iitis/just-the-docs
# remote_theme: thealjey/just-the-docs
remote_theme: pdmosses/just-the-docs@rec-nav-2
color_scheme: light
logo: /assets/logo.png
search_enabled: false
aux_links:
  "numericalshadow.org on GitHub":
    - "//github.com/numericalshadow/numericalshadow.org"

aux_links_new_tab: true

exclude: ["docker-compose.yml", "deploy.sh", "cleanup.py", "old_menu.png"]
